[default]
TITLE="Bolg Flask"

SQLALCHEMY_DATABASE_URI="sqlite:///db.sqlite"


EXTENSIONS = [
    "app.ext.flask_sql_alchemy:init_app",

    "app.blueprints.web:init_app",
    "app.blueprints.api:init_app"
]

[production]
