[default]
TITLE="Bolg Flask"

SQLALCHEMY_DATABASE_URI="sqlite:///db.sqlite"
SQLALCHEMY_TRACK_MODIFICATIONS = false

SECRET_KEY="secret"
WTF_CSRF_SECRET_KEY="secret"


EXTENSIONS = [
    "app.ext.flask_sql_alchemy:init_app",
    "app.ext.flask_migration:init_app",
    "app.ext.commands:init_commands",
    "app.ext.flask_wtf:init_app",

    "app.blueprints.web:init_app",
    "app.blueprints.api:init_app"
]

[production]
